import type { Locale } from "./i18n-config";

export interface Country {
  name: string;
  flag: string;
}

export const COUNTRIES: Country[] = [
  { name: "Afghanistan", flag: "🇦🇫" },
  { name: "Albania", flag: "🇦🇱" },
  { name: "Algeria", flag: "🇩🇿" },
  { name: "Andorra", flag: "🇦🇩" },
  { name: "Angola", flag: "🇦🇴" },
  { name: "Antigua and Barbuda", flag: "🇦🇬" },
  { name: "Argentina", flag: "🇦🇷" },
  { name: "Armenia", flag: "🇦🇲" },
  { name: "Australia", flag: "🇦🇺" },
  { name: "Austria", flag: "🇦🇹" },
  { name: "Azerbaijan", flag: "🇦🇿" },
  { name: "Bahamas", flag: "🇧🇸" },
  { name: "Bahrain", flag: "🇧🇭" },
  { name: "Bangladesh", flag: "🇧🇩" },
  { name: "Barbados", flag: "🇧🇧" },
  { name: "Belarus", flag: "🇧🇾" },
  { name: "Belgium", flag: "🇧🇪" },
  { name: "Belize", flag: "🇧🇿" },
  { name: "Benin", flag: "🇧🇯" },
  { name: "Bhutan", flag: "🇧🇹" },
  { name: "Bolivia", flag: "🇧🇴" },
  { name: "Bosnia and Herzegovina", flag: "🇧🇦" },
  { name: "Botswana", flag: "🇧🇼" },
  { name: "Brazil", flag: "🇧🇷" },
  { name: "Brunei", flag: "🇧🇳" },
  { name: "Bulgaria", flag: "🇧🇬" },
  { name: "Burkina Faso", flag: "🇧🇫" },
  { name: "Burundi", flag: "🇧🇮" },
  { name: "Cabo Verde", flag: "🇨🇻" },
  { name: "Cambodia", flag: "🇰🇭" },
  { name: "Cameroon", flag: "🇨🇲" },
  { name: "Canada", flag: "🇨🇦" },
  { name: "Central African Republic", flag: "🇨🇫" },
  { name: "Chad", flag: "🇹🇩" },
  { name: "Chile", flag: "🇨🇱" },
  { name: "China", flag: "🇨🇳" },
  { name: "Colombia", flag: "🇨🇴" },
  { name: "Comoros", flag: "🇰🇲" },
  { name: "Congo", flag: "🇨🇬" },
  { name: "Costa Rica", flag: "🇨🇷" },
  { name: "Croatia", flag: "🇭🇷" },
  { name: "Cuba", flag: "🇨🇺" },
  { name: "Cyprus", flag: "🇨🇾" },
  { name: "Czechia", flag: "🇨🇿" },
  { name: "Democratic Republic of the Congo", flag: "🇨🇩" },
  { name: "Denmark", flag: "🇩🇰" },
  { name: "Djibouti", flag: "🇩🇯" },
  { name: "Dominica", flag: "🇩🇲" },
  { name: "Dominican Republic", flag: "🇩🇴" },
  { name: "Ecuador", flag: "🇪🇨" },
  { name: "Egypt", flag: "🇪🇬" },
  { name: "El Salvador", flag: "🇸🇻" },
  { name: "Equatorial Guinea", flag: "🇬🇶" },
  { name: "Eritrea", flag: "🇪🇷" },
  { name: "Estonia", flag: "🇪🇪" },
  { name: "Eswatini", flag: "🇸🇿" },
  { name: "Ethiopia", flag: "🇪🇹" },
  { name: "Fiji", flag: "🇫🇯" },
  { name: "Finland", flag: "🇫🇮" },
  { name: "France", flag: "🇫🇷" },
  { name: "Gabon", flag: "🇬🇦" },
  { name: "Gambia", flag: "🇬🇲" },
  { name: "Georgia", flag: "🇬🇪" },
  { name: "Germany", flag: "🇩🇪" },
  { name: "Ghana", flag: "🇬🇭" },
  { name: "Greece", flag: "🇬🇷" },
  { name: "Grenada", flag: "🇬🇩" },
  { name: "Guatemala", flag: "🇬🇹" },
  { name: "Guinea", flag: "🇬🇳" },
  { name: "Guinea-Bissau", flag: "🇬🇼" },
  { name: "Guyana", flag: "🇬🇾" },
  { name: "Haiti", flag: "🇭🇹" },
  { name: "Honduras", flag: "🇭🇳" },
  { name: "Hungary", flag: "🇭🇺" },
  { name: "Iceland", flag: "🇮🇸" },
  { name: "India", flag: "🇮🇳" },
  { name: "Indonesia", flag: "🇮🇩" },
  { name: "Iran", flag: "🇮🇷" },
  { name: "Iraq", flag: "🇮🇶" },
  { name: "Ireland", flag: "🇮🇪" },
  { name: "Israel", flag: "🇮🇱" },
  { name: "Italy", flag: "🇮🇹" },
  { name: "Ivory Coast", flag: "🇨🇮" },
  { name: "Jamaica", flag: "🇯🇲" },
  { name: "Japan", flag: "🇯🇵" },
  { name: "Jordan", flag: "🇯🇴" },
  { name: "Kazakhstan", flag: "🇰🇿" },
  { name: "Kenya", flag: "🇰🇪" },
  { name: "Kiribati", flag: "🇰🇮" },
  { name: "Kosovo", flag: "🇽🇰" },
  { name: "Kuwait", flag: "🇰🇼" },
  { name: "Kyrgyzstan", flag: "🇰🇬" },
  { name: "Laos", flag: "🇱🇦" },
  { name: "Latvia", flag: "🇱🇻" },
  { name: "Lebanon", flag: "🇱🇧" },
  { name: "Lesotho", flag: "🇱🇸" },
  { name: "Liberia", flag: "🇱🇷" },
  { name: "Libya", flag: "🇱🇾" },
  { name: "Liechtenstein", flag: "🇱🇮" },
  { name: "Lithuania", flag: "🇱🇹" },
  { name: "Luxembourg", flag: "🇱🇺" },
  { name: "Madagascar", flag: "🇲🇬" },
  { name: "Malawi", flag: "🇲🇼" },
  { name: "Malaysia", flag: "🇲🇾" },
  { name: "Maldives", flag: "🇲🇻" },
  { name: "Mali", flag: "🇲🇱" },
  { name: "Malta", flag: "🇲🇹" },
  { name: "Marshall Islands", flag: "🇲🇭" },
  { name: "Mauritania", flag: "🇲🇷" },
  { name: "Mauritius", flag: "🇲🇺" },
  { name: "Mexico", flag: "🇲🇽" },
  { name: "Micronesia", flag: "🇫🇲" },
  { name: "Moldova", flag: "🇲🇩" },
  { name: "Monaco", flag: "🇲🇨" },
  { name: "Mongolia", flag: "🇲🇳" },
  { name: "Montenegro", flag: "🇲🇪" },
  { name: "Morocco", flag: "🇲🇦" },
  { name: "Mozambique", flag: "🇲🇿" },
  { name: "Myanmar", flag: "🇲🇲" },
  { name: "Namibia", flag: "🇳🇦" },
  { name: "Nauru", flag: "🇳🇷" },
  { name: "Nepal", flag: "🇳🇵" },
  { name: "Netherlands", flag: "🇳🇱" },
  { name: "New Zealand", flag: "🇳🇿" },
  { name: "Nicaragua", flag: "🇳🇮" },
  { name: "Niger", flag: "🇳🇪" },
  { name: "Nigeria", flag: "🇳🇬" },
  { name: "North Korea", flag: "🇰🇵" },
  { name: "North Macedonia", flag: "🇲🇰" },
  { name: "Norway", flag: "🇳🇴" },
  { name: "Oman", flag: "🇴🇲" },
  { name: "Pakistan", flag: "🇵🇰" },
  { name: "Palau", flag: "🇵🇼" },
  { name: "Palestine", flag: "🇵🇸" },
  { name: "Panama", flag: "🇵🇦" },
  { name: "Papua New Guinea", flag: "🇵🇬" },
  { name: "Paraguay", flag: "🇵🇾" },
  { name: "Peru", flag: "🇵🇪" },
  { name: "Philippines", flag: "🇵🇭" },
  { name: "Poland", flag: "🇵🇱" },
  { name: "Portugal", flag: "🇵🇹" },
  { name: "Qatar", flag: "🇶🇦" },
  { name: "Romania", flag: "🇷🇴" },
  { name: "Russia", flag: "🇷🇺" },
  { name: "Rwanda", flag: "🇷🇼" },
  { name: "Saint Kitts and Nevis", flag: "🇰🇳" },
  { name: "Saint Lucia", flag: "🇱🇨" },
  { name: "Saint Vincent and the Grenadines", flag: "🇻🇨" },
  { name: "Samoa", flag: "🇼🇸" },
  { name: "San Marino", flag: "🇸🇲" },
  { name: "Sao Tome and Principe", flag: "🇸🇹" },
  { name: "Saudi Arabia", flag: "🇸🇦" },
  { name: "Senegal", flag: "🇸🇳" },
  { name: "Serbia", flag: "🇷🇸" },
  { name: "Seychelles", flag: "🇸🇨" },
  { name: "Sierra Leone", flag: "🇸🇱" },
  { name: "Singapore", flag: "🇸🇬" },
  { name: "Slovakia", flag: "🇸🇰" },
  { name: "Slovenia", flag: "🇸🇮" },
  { name: "Solomon Islands", flag: "🇸🇧" },
  { name: "Somalia", flag: "🇸🇴" },
  { name: "South Africa", flag: "🇿🇦" },
  { name: "South Korea", flag: "🇰🇷" },
  { name: "South Sudan", flag: "🇸🇸" },
  { name: "Spain", flag: "🇪🇸" },
  { name: "Sri Lanka", flag: "🇱🇰" },
  { name: "Sudan", flag: "🇸🇩" },
  { name: "Suriname", flag: "🇸🇷" },
  { name: "Sweden", flag: "🇸🇪" },
  { name: "Switzerland", flag: "🇨🇭" },
  { name: "Syria", flag: "🇸🇾" },
  { name: "Taiwan", flag: "🇹🇼" },
  { name: "Tajikistan", flag: "🇹🇯" },
  { name: "Tanzania", flag: "🇹🇿" },
  { name: "Thailand", flag: "🇹🇭" },
  { name: "Timor-Leste", flag: "🇹🇱" },
  { name: "Togo", flag: "🇹🇬" },
  { name: "Tonga", flag: "🇹🇴" },
  { name: "Trinidad and Tobago", flag: "🇹🇹" },
  { name: "Tunisia", flag: "🇹🇳" },
  { name: "Turkey", flag: "🇹🇷" },
  { name: "Turkmenistan", flag: "🇹🇲" },
  { name: "Tuvalu", flag: "🇹🇻" },
  { name: "Uganda", flag: "🇺🇬" },
  { name: "Ukraine", flag: "🇺🇦" },
  { name: "United Arab Emirates", flag: "🇦🇪" },
  { name: "United Kingdom", flag: "🇬🇧" },
  { name: "United States", flag: "🇺🇸" },
  { name: "Uruguay", flag: "🇺🇾" },
  { name: "Uzbekistan", flag: "🇺🇿" },
  { name: "Vanuatu", flag: "🇻🇺" },
  { name: "Vatican City", flag: "🇻🇦" },
  { name: "Venezuela", flag: "🇻🇪" },
  { name: "Vietnam", flag: "🇻🇳" },
  { name: "Yemen", flag: "🇾🇪" },
  { name: "Zambia", flag: "🇿🇲" },
  { name: "Zimbabwe", flag: "🇿🇼" },
];

export const COUNTRY_NAMES: string[] = COUNTRIES.map((c) => c.name);

const FLAG_BY_NAME = new Map(COUNTRIES.map((c) => [c.name, c.flag]));

export function countryFlag(name: string): string {
  return FLAG_BY_NAME.get(name) ?? "";
}

export function isValidCountry(name: string): boolean {
  return FLAG_BY_NAME.has(name);
}

// Localized display names, keyed by the canonical English name that guest
// records actually store (isValidCountry/onChange always deal in the
// English name above — only the label shown to the user is translated).
const COUNTRY_NAME_TRANSLATIONS: Record<Exclude<Locale, "en">, Record<string, string>> = {
  de: {
    Afghanistan: "Afghanistan",
    Albania: "Albanien",
    Algeria: "Algerien",
    Andorra: "Andorra",
    Angola: "Angola",
    "Antigua and Barbuda": "Antigua und Barbuda",
    Argentina: "Argentinien",
    Armenia: "Armenien",
    Australia: "Australien",
    Austria: "Österreich",
    Azerbaijan: "Aserbaidschan",
    Bahamas: "Bahamas",
    Bahrain: "Bahrain",
    Bangladesh: "Bangladesch",
    Barbados: "Barbados",
    Belarus: "Belarus",
    Belgium: "Belgien",
    Belize: "Belize",
    Benin: "Benin",
    Bhutan: "Bhutan",
    Bolivia: "Bolivien",
    "Bosnia and Herzegovina": "Bosnien und Herzegowina",
    Botswana: "Botsuana",
    Brazil: "Brasilien",
    Brunei: "Brunei",
    Bulgaria: "Bulgarien",
    "Burkina Faso": "Burkina Faso",
    Burundi: "Burundi",
    "Cabo Verde": "Kap Verde",
    Cambodia: "Kambodscha",
    Cameroon: "Kamerun",
    Canada: "Kanada",
    "Central African Republic": "Zentralafrikanische Republik",
    Chad: "Tschad",
    Chile: "Chile",
    China: "China",
    Colombia: "Kolumbien",
    Comoros: "Komoren",
    Congo: "Kongo",
    "Costa Rica": "Costa Rica",
    Croatia: "Kroatien",
    Cuba: "Kuba",
    Cyprus: "Zypern",
    Czechia: "Tschechien",
    "Democratic Republic of the Congo": "Demokratische Republik Kongo",
    Denmark: "Dänemark",
    Djibouti: "Dschibuti",
    Dominica: "Dominica",
    "Dominican Republic": "Dominikanische Republik",
    Ecuador: "Ecuador",
    Egypt: "Ägypten",
    "El Salvador": "El Salvador",
    "Equatorial Guinea": "Äquatorialguinea",
    Eritrea: "Eritrea",
    Estonia: "Estland",
    Eswatini: "Eswatini",
    Ethiopia: "Äthiopien",
    Fiji: "Fidschi",
    Finland: "Finnland",
    France: "Frankreich",
    Gabon: "Gabun",
    Gambia: "Gambia",
    Georgia: "Georgien",
    Germany: "Deutschland",
    Ghana: "Ghana",
    Greece: "Griechenland",
    Grenada: "Grenada",
    Guatemala: "Guatemala",
    Guinea: "Guinea",
    "Guinea-Bissau": "Guinea-Bissau",
    Guyana: "Guyana",
    Haiti: "Haiti",
    Honduras: "Honduras",
    Hungary: "Ungarn",
    Iceland: "Island",
    India: "Indien",
    Indonesia: "Indonesien",
    Iran: "Iran",
    Iraq: "Irak",
    Ireland: "Irland",
    Israel: "Israel",
    Italy: "Italien",
    "Ivory Coast": "Elfenbeinküste",
    Jamaica: "Jamaika",
    Japan: "Japan",
    Jordan: "Jordanien",
    Kazakhstan: "Kasachstan",
    Kenya: "Kenia",
    Kiribati: "Kiribati",
    Kosovo: "Kosovo",
    Kuwait: "Kuwait",
    Kyrgyzstan: "Kirgisistan",
    Laos: "Laos",
    Latvia: "Lettland",
    Lebanon: "Libanon",
    Lesotho: "Lesotho",
    Liberia: "Liberia",
    Libya: "Libyen",
    Liechtenstein: "Liechtenstein",
    Lithuania: "Litauen",
    Luxembourg: "Luxemburg",
    Madagascar: "Madagaskar",
    Malawi: "Malawi",
    Malaysia: "Malaysia",
    Maldives: "Malediven",
    Mali: "Mali",
    Malta: "Malta",
    "Marshall Islands": "Marshallinseln",
    Mauritania: "Mauretanien",
    Mauritius: "Mauritius",
    Mexico: "Mexiko",
    Micronesia: "Mikronesien",
    Moldova: "Moldau",
    Monaco: "Monaco",
    Mongolia: "Mongolei",
    Montenegro: "Montenegro",
    Morocco: "Marokko",
    Mozambique: "Mosambik",
    Myanmar: "Myanmar",
    Namibia: "Namibia",
    Nauru: "Nauru",
    Nepal: "Nepal",
    Netherlands: "Niederlande",
    "New Zealand": "Neuseeland",
    Nicaragua: "Nicaragua",
    Niger: "Niger",
    Nigeria: "Nigeria",
    "North Korea": "Nordkorea",
    "North Macedonia": "Nordmazedonien",
    Norway: "Norwegen",
    Oman: "Oman",
    Pakistan: "Pakistan",
    Palau: "Palau",
    Palestine: "Palästina",
    Panama: "Panama",
    "Papua New Guinea": "Papua-Neuguinea",
    Paraguay: "Paraguay",
    Peru: "Peru",
    Philippines: "Philippinen",
    Poland: "Polen",
    Portugal: "Portugal",
    Qatar: "Katar",
    Romania: "Rumänien",
    Russia: "Russland",
    Rwanda: "Ruanda",
    "Saint Kitts and Nevis": "St. Kitts und Nevis",
    "Saint Lucia": "St. Lucia",
    "Saint Vincent and the Grenadines": "St. Vincent und die Grenadinen",
    Samoa: "Samoa",
    "San Marino": "San Marino",
    "Sao Tome and Principe": "São Tomé und Príncipe",
    "Saudi Arabia": "Saudi-Arabien",
    Senegal: "Senegal",
    Serbia: "Serbien",
    Seychelles: "Seychellen",
    "Sierra Leone": "Sierra Leone",
    Singapore: "Singapur",
    Slovakia: "Slowakei",
    Slovenia: "Slowenien",
    "Solomon Islands": "Salomonen",
    Somalia: "Somalia",
    "South Africa": "Südafrika",
    "South Korea": "Südkorea",
    "South Sudan": "Südsudan",
    Spain: "Spanien",
    "Sri Lanka": "Sri Lanka",
    Sudan: "Sudan",
    Suriname: "Suriname",
    Sweden: "Schweden",
    Switzerland: "Schweiz",
    Syria: "Syrien",
    Taiwan: "Taiwan",
    Tajikistan: "Tadschikistan",
    Tanzania: "Tansania",
    Thailand: "Thailand",
    "Timor-Leste": "Osttimor",
    Togo: "Togo",
    Tonga: "Tonga",
    "Trinidad and Tobago": "Trinidad und Tobago",
    Tunisia: "Tunesien",
    Turkey: "Türkei",
    Turkmenistan: "Turkmenistan",
    Tuvalu: "Tuvalu",
    Uganda: "Uganda",
    Ukraine: "Ukraine",
    "United Arab Emirates": "Vereinigte Arabische Emirate",
    "United Kingdom": "Vereinigtes Königreich",
    "United States": "Vereinigte Staaten",
    Uruguay: "Uruguay",
    Uzbekistan: "Usbekistan",
    Vanuatu: "Vanuatu",
    "Vatican City": "Vatikanstadt",
    Venezuela: "Venezuela",
    Vietnam: "Vietnam",
    Yemen: "Jemen",
    Zambia: "Sambia",
    Zimbabwe: "Simbabwe",
  },
  fr: {
    Afghanistan: "Afghanistan",
    Albania: "Albanie",
    Algeria: "Algérie",
    Andorra: "Andorre",
    Angola: "Angola",
    "Antigua and Barbuda": "Antigua-et-Barbuda",
    Argentina: "Argentine",
    Armenia: "Arménie",
    Australia: "Australie",
    Austria: "Autriche",
    Azerbaijan: "Azerbaïdjan",
    Bahamas: "Bahamas",
    Bahrain: "Bahreïn",
    Bangladesh: "Bangladesh",
    Barbados: "Barbade",
    Belarus: "Biélorussie",
    Belgium: "Belgique",
    Belize: "Belize",
    Benin: "Bénin",
    Bhutan: "Bhoutan",
    Bolivia: "Bolivie",
    "Bosnia and Herzegovina": "Bosnie-Herzégovine",
    Botswana: "Botswana",
    Brazil: "Brésil",
    Brunei: "Brunei",
    Bulgaria: "Bulgarie",
    "Burkina Faso": "Burkina Faso",
    Burundi: "Burundi",
    "Cabo Verde": "Cap-Vert",
    Cambodia: "Cambodge",
    Cameroon: "Cameroun",
    Canada: "Canada",
    "Central African Republic": "République centrafricaine",
    Chad: "Tchad",
    Chile: "Chili",
    China: "Chine",
    Colombia: "Colombie",
    Comoros: "Comores",
    Congo: "Congo",
    "Costa Rica": "Costa Rica",
    Croatia: "Croatie",
    Cuba: "Cuba",
    Cyprus: "Chypre",
    Czechia: "Tchéquie",
    "Democratic Republic of the Congo": "République démocratique du Congo",
    Denmark: "Danemark",
    Djibouti: "Djibouti",
    Dominica: "Dominique",
    "Dominican Republic": "République dominicaine",
    Ecuador: "Équateur",
    Egypt: "Égypte",
    "El Salvador": "Salvador",
    "Equatorial Guinea": "Guinée équatoriale",
    Eritrea: "Érythrée",
    Estonia: "Estonie",
    Eswatini: "Eswatini",
    Ethiopia: "Éthiopie",
    Fiji: "Fidji",
    Finland: "Finlande",
    France: "France",
    Gabon: "Gabon",
    Gambia: "Gambie",
    Georgia: "Géorgie",
    Germany: "Allemagne",
    Ghana: "Ghana",
    Greece: "Grèce",
    Grenada: "Grenade",
    Guatemala: "Guatemala",
    Guinea: "Guinée",
    "Guinea-Bissau": "Guinée-Bissau",
    Guyana: "Guyana",
    Haiti: "Haïti",
    Honduras: "Honduras",
    Hungary: "Hongrie",
    Iceland: "Islande",
    India: "Inde",
    Indonesia: "Indonésie",
    Iran: "Iran",
    Iraq: "Irak",
    Ireland: "Irlande",
    Israel: "Israël",
    Italy: "Italie",
    "Ivory Coast": "Côte d'Ivoire",
    Jamaica: "Jamaïque",
    Japan: "Japon",
    Jordan: "Jordanie",
    Kazakhstan: "Kazakhstan",
    Kenya: "Kenya",
    Kiribati: "Kiribati",
    Kosovo: "Kosovo",
    Kuwait: "Koweït",
    Kyrgyzstan: "Kirghizistan",
    Laos: "Laos",
    Latvia: "Lettonie",
    Lebanon: "Liban",
    Lesotho: "Lesotho",
    Liberia: "Libéria",
    Libya: "Libye",
    Liechtenstein: "Liechtenstein",
    Lithuania: "Lituanie",
    Luxembourg: "Luxembourg",
    Madagascar: "Madagascar",
    Malawi: "Malawi",
    Malaysia: "Malaisie",
    Maldives: "Maldives",
    Mali: "Mali",
    Malta: "Malte",
    "Marshall Islands": "Îles Marshall",
    Mauritania: "Mauritanie",
    Mauritius: "Maurice",
    Mexico: "Mexique",
    Micronesia: "Micronésie",
    Moldova: "Moldavie",
    Monaco: "Monaco",
    Mongolia: "Mongolie",
    Montenegro: "Monténégro",
    Morocco: "Maroc",
    Mozambique: "Mozambique",
    Myanmar: "Myanmar",
    Namibia: "Namibie",
    Nauru: "Nauru",
    Nepal: "Népal",
    Netherlands: "Pays-Bas",
    "New Zealand": "Nouvelle-Zélande",
    Nicaragua: "Nicaragua",
    Niger: "Niger",
    Nigeria: "Nigeria",
    "North Korea": "Corée du Nord",
    "North Macedonia": "Macédoine du Nord",
    Norway: "Norvège",
    Oman: "Oman",
    Pakistan: "Pakistan",
    Palau: "Palaos",
    Palestine: "Palestine",
    Panama: "Panama",
    "Papua New Guinea": "Papouasie-Nouvelle-Guinée",
    Paraguay: "Paraguay",
    Peru: "Pérou",
    Philippines: "Philippines",
    Poland: "Pologne",
    Portugal: "Portugal",
    Qatar: "Qatar",
    Romania: "Roumanie",
    Russia: "Russie",
    Rwanda: "Rwanda",
    "Saint Kitts and Nevis": "Saint-Christophe-et-Niévès",
    "Saint Lucia": "Sainte-Lucie",
    "Saint Vincent and the Grenadines": "Saint-Vincent-et-les-Grenadines",
    Samoa: "Samoa",
    "San Marino": "Saint-Marin",
    "Sao Tome and Principe": "Sao Tomé-et-Principe",
    "Saudi Arabia": "Arabie saoudite",
    Senegal: "Sénégal",
    Serbia: "Serbie",
    Seychelles: "Seychelles",
    "Sierra Leone": "Sierra Leone",
    Singapore: "Singapour",
    Slovakia: "Slovaquie",
    Slovenia: "Slovénie",
    "Solomon Islands": "Îles Salomon",
    Somalia: "Somalie",
    "South Africa": "Afrique du Sud",
    "South Korea": "Corée du Sud",
    "South Sudan": "Soudan du Sud",
    Spain: "Espagne",
    "Sri Lanka": "Sri Lanka",
    Sudan: "Soudan",
    Suriname: "Suriname",
    Sweden: "Suède",
    Switzerland: "Suisse",
    Syria: "Syrie",
    Taiwan: "Taïwan",
    Tajikistan: "Tadjikistan",
    Tanzania: "Tanzanie",
    Thailand: "Thaïlande",
    "Timor-Leste": "Timor oriental",
    Togo: "Togo",
    Tonga: "Tonga",
    "Trinidad and Tobago": "Trinité-et-Tobago",
    Tunisia: "Tunisie",
    Turkey: "Turquie",
    Turkmenistan: "Turkménistan",
    Tuvalu: "Tuvalu",
    Uganda: "Ouganda",
    Ukraine: "Ukraine",
    "United Arab Emirates": "Émirats arabes unis",
    "United Kingdom": "Royaume-Uni",
    "United States": "États-Unis",
    Uruguay: "Uruguay",
    Uzbekistan: "Ouzbékistan",
    Vanuatu: "Vanuatu",
    "Vatican City": "Cité du Vatican",
    Venezuela: "Venezuela",
    Vietnam: "Viêt Nam",
    Yemen: "Yémen",
    Zambia: "Zambie",
    Zimbabwe: "Zimbabwe",
  },
  it: {
    Afghanistan: "Afghanistan",
    Albania: "Albania",
    Algeria: "Algeria",
    Andorra: "Andorra",
    Angola: "Angola",
    "Antigua and Barbuda": "Antigua e Barbuda",
    Argentina: "Argentina",
    Armenia: "Armenia",
    Australia: "Australia",
    Austria: "Austria",
    Azerbaijan: "Azerbaigian",
    Bahamas: "Bahamas",
    Bahrain: "Bahrein",
    Bangladesh: "Bangladesh",
    Barbados: "Barbados",
    Belarus: "Bielorussia",
    Belgium: "Belgio",
    Belize: "Belize",
    Benin: "Benin",
    Bhutan: "Bhutan",
    Bolivia: "Bolivia",
    "Bosnia and Herzegovina": "Bosnia ed Erzegovina",
    Botswana: "Botswana",
    Brazil: "Brasile",
    Brunei: "Brunei",
    Bulgaria: "Bulgaria",
    "Burkina Faso": "Burkina Faso",
    Burundi: "Burundi",
    "Cabo Verde": "Capo Verde",
    Cambodia: "Cambogia",
    Cameroon: "Camerun",
    Canada: "Canada",
    "Central African Republic": "Repubblica Centrafricana",
    Chad: "Ciad",
    Chile: "Cile",
    China: "Cina",
    Colombia: "Colombia",
    Comoros: "Comore",
    Congo: "Congo",
    "Costa Rica": "Costa Rica",
    Croatia: "Croazia",
    Cuba: "Cuba",
    Cyprus: "Cipro",
    Czechia: "Cechia",
    "Democratic Republic of the Congo": "Repubblica Democratica del Congo",
    Denmark: "Danimarca",
    Djibouti: "Gibuti",
    Dominica: "Dominica",
    "Dominican Republic": "Repubblica Dominicana",
    Ecuador: "Ecuador",
    Egypt: "Egitto",
    "El Salvador": "El Salvador",
    "Equatorial Guinea": "Guinea Equatoriale",
    Eritrea: "Eritrea",
    Estonia: "Estonia",
    Eswatini: "Eswatini",
    Ethiopia: "Etiopia",
    Fiji: "Figi",
    Finland: "Finlandia",
    France: "Francia",
    Gabon: "Gabon",
    Gambia: "Gambia",
    Georgia: "Georgia",
    Germany: "Germania",
    Ghana: "Ghana",
    Greece: "Grecia",
    Grenada: "Grenada",
    Guatemala: "Guatemala",
    Guinea: "Guinea",
    "Guinea-Bissau": "Guinea-Bissau",
    Guyana: "Guyana",
    Haiti: "Haiti",
    Honduras: "Honduras",
    Hungary: "Ungheria",
    Iceland: "Islanda",
    India: "India",
    Indonesia: "Indonesia",
    Iran: "Iran",
    Iraq: "Iraq",
    Ireland: "Irlanda",
    Israel: "Israele",
    Italy: "Italia",
    "Ivory Coast": "Costa d'Avorio",
    Jamaica: "Giamaica",
    Japan: "Giappone",
    Jordan: "Giordania",
    Kazakhstan: "Kazakistan",
    Kenya: "Kenya",
    Kiribati: "Kiribati",
    Kosovo: "Kosovo",
    Kuwait: "Kuwait",
    Kyrgyzstan: "Kirghizistan",
    Laos: "Laos",
    Latvia: "Lettonia",
    Lebanon: "Libano",
    Lesotho: "Lesotho",
    Liberia: "Liberia",
    Libya: "Libia",
    Liechtenstein: "Liechtenstein",
    Lithuania: "Lituania",
    Luxembourg: "Lussemburgo",
    Madagascar: "Madagascar",
    Malawi: "Malawi",
    Malaysia: "Malaysia",
    Maldives: "Maldive",
    Mali: "Mali",
    Malta: "Malta",
    "Marshall Islands": "Isole Marshall",
    Mauritania: "Mauritania",
    Mauritius: "Mauritius",
    Mexico: "Messico",
    Micronesia: "Micronesia",
    Moldova: "Moldavia",
    Monaco: "Monaco",
    Mongolia: "Mongolia",
    Montenegro: "Montenegro",
    Morocco: "Marocco",
    Mozambique: "Mozambico",
    Myanmar: "Myanmar",
    Namibia: "Namibia",
    Nauru: "Nauru",
    Nepal: "Nepal",
    Netherlands: "Paesi Bassi",
    "New Zealand": "Nuova Zelanda",
    Nicaragua: "Nicaragua",
    Niger: "Niger",
    Nigeria: "Nigeria",
    "North Korea": "Corea del Nord",
    "North Macedonia": "Macedonia del Nord",
    Norway: "Norvegia",
    Oman: "Oman",
    Pakistan: "Pakistan",
    Palau: "Palau",
    Palestine: "Palestina",
    Panama: "Panama",
    "Papua New Guinea": "Papua Nuova Guinea",
    Paraguay: "Paraguay",
    Peru: "Perù",
    Philippines: "Filippine",
    Poland: "Polonia",
    Portugal: "Portogallo",
    Qatar: "Qatar",
    Romania: "Romania",
    Russia: "Russia",
    Rwanda: "Ruanda",
    "Saint Kitts and Nevis": "Saint Kitts e Nevis",
    "Saint Lucia": "Santa Lucia",
    "Saint Vincent and the Grenadines": "Saint Vincent e Grenadine",
    Samoa: "Samoa",
    "San Marino": "San Marino",
    "Sao Tome and Principe": "São Tomé e Príncipe",
    "Saudi Arabia": "Arabia Saudita",
    Senegal: "Senegal",
    Serbia: "Serbia",
    Seychelles: "Seychelles",
    "Sierra Leone": "Sierra Leone",
    Singapore: "Singapore",
    Slovakia: "Slovacchia",
    Slovenia: "Slovenia",
    "Solomon Islands": "Isole Salomone",
    Somalia: "Somalia",
    "South Africa": "Sudafrica",
    "South Korea": "Corea del Sud",
    "South Sudan": "Sudan del Sud",
    Spain: "Spagna",
    "Sri Lanka": "Sri Lanka",
    Sudan: "Sudan",
    Suriname: "Suriname",
    Sweden: "Svezia",
    Switzerland: "Svizzera",
    Syria: "Siria",
    Taiwan: "Taiwan",
    Tajikistan: "Tagikistan",
    Tanzania: "Tanzania",
    Thailand: "Thailandia",
    "Timor-Leste": "Timor Est",
    Togo: "Togo",
    Tonga: "Tonga",
    "Trinidad and Tobago": "Trinidad e Tobago",
    Tunisia: "Tunisia",
    Turkey: "Turchia",
    Turkmenistan: "Turkmenistan",
    Tuvalu: "Tuvalu",
    Uganda: "Uganda",
    Ukraine: "Ucraina",
    "United Arab Emirates": "Emirati Arabi Uniti",
    "United Kingdom": "Regno Unito",
    "United States": "Stati Uniti",
    Uruguay: "Uruguay",
    Uzbekistan: "Uzbekistan",
    Vanuatu: "Vanuatu",
    "Vatican City": "Città del Vaticano",
    Venezuela: "Venezuela",
    Vietnam: "Vietnam",
    Yemen: "Yemen",
    Zambia: "Zambia",
    Zimbabwe: "Zimbabwe",
  },
};

export function localizedCountryName(name: string, locale: Locale): string {
  if (locale === "en") return name;
  return COUNTRY_NAME_TRANSLATIONS[locale][name] ?? name;
}
